codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: true

flags:
  go:
    paths:
      - go/
    carryforward: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true
