[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.3.0
board = uno
framework = arduino
lib_deps = symlink://../../..
build_flags =
  -DADXL355_CPP_NO_EXCEPTIONS=1
  -DADXL355_EMBEDDED_COMPILE_FIXTURE=1
