from __future__ import annotations

import re
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

from scripts.check_public_api import snapshot
from scripts.generate_api_reference import LANGUAGES, OUTPUT_ROOT, verify


REPO_ROOT = Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
HARDWARE = REPO_ROOT / "docs" / "hardware-testing.md"
MEDIA_ROOT = REPO_ROOT / "docs" / "media"
SPI_SVG = MEDIA_ROOT / "raspberry-pi-5-spi-adxl355.svg"
I2C_SVG = MEDIA_ROOT / "raspberry-pi-5-i2c-adxl355.svg"
C_HEADER = REPO_ROOT / "c" / "include" / "adxl355" / "adxl355.h"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ci.yml"


class ApiReferenceTests(unittest.TestCase):
    def test_generated_references_match_public_api_surface(self) -> None:
        verify()
        surfaces = snapshot(REPO_ROOT)["surfaces"]
        self.assertEqual({language.key for language in LANGUAGES}, set(surfaces))
        self.assertEqual(
            {path.name for path in OUTPUT_ROOT.glob("*.md")},
            {"README.md", *(f"{language.key}.md" for language in LANGUAGES)},
        )
        index = (OUTPUT_ROOT / "README.md").read_text(encoding="utf-8")
        for language in LANGUAGES:
            page = (OUTPUT_ROOT / f"{language.key}.md").read_text(encoding="utf-8")
            self.assertIn("Generated by scripts/generate_api_reference.py", page)
            self.assertIn(language.capability, page)
            self.assertIn(language.limitations, page)
            self.assertIn(f"{len(surfaces[language.key])} |", index)
            for source in language.sources:
                self.assertTrue((REPO_ROOT / source).is_file(), source)
                self.assertIn(f"../../{source}", page)

    def test_generated_reference_verification_is_required(self) -> None:
        workflow = CI_WORKFLOW.read_text(encoding="utf-8")
        self.assertIn("Verify generated API references", workflow)
        self.assertIn("python scripts/generate_api_reference.py --verify", workflow)
        testing = (REPO_ROOT / "docs" / "testing.md").read_text(encoding="utf-8")
        self.assertIn("## Generated API references", testing)
        self.assertIn("python scripts/generate_api_reference.py --verify", testing)
        self.assertIn("docs/api/README.md", README.read_text(encoding="utf-8"))

    def test_public_c_functions_have_doxygen_return_contracts(self) -> None:
        text = C_HEADER.read_text(encoding="utf-8")
        declarations = list(
            re.finditer(
                r"(?m)^(?:adxl355_status_t|int32_t|float|const char \*)\s+"
                r"(?P<name>adxl355_[A-Za-z0-9_]+)\s*\(",
                text,
            )
        )
        self.assertGreaterEqual(len(declarations), 20)
        for declaration in declarations:
            prefix = text[: declaration.start()].rstrip()
            start = prefix.rfind("/**")
            end = prefix.rfind("*/")
            self.assertGreaterEqual(start, 0, declaration.group("name"))
            self.assertGreater(end, start, declaration.group("name"))
            comment = prefix[start : end + 2]
            self.assertIn("@return", comment, declaration.group("name"))
        self.assertIn("Stable status values returned by the public C API", text)
        self.assertIn("output-data-rate encodings", text)

    def test_spi_svg_is_accessible_local_and_license_safe(self) -> None:
        tree = ET.parse(SPI_SVG)
        root = tree.getroot()
        namespace = {"svg": "http://www.w3.org/2000/svg"}
        title = root.find("svg:title", namespace)
        description = root.find("svg:desc", namespace)
        self.assertIsNotNone(title)
        self.assertIsNotNone(description)
        self.assertGreater(len((description.text or "").split()), 35)
        rendered = SPI_SVG.read_text(encoding="utf-8")
        for phrase in (
            "Pin 1 · 3V3",
            "Pin 6 · GND",
            "Pin 23 · GPIO11 / SCLK",
            "Pin 19 · GPIO10 / MOSI",
            "Pin 21 · GPIO9 / MISO",
            "Pin 24 · GPIO8 / CE0",
            "Pin 11 · GPIO17 (optional)",
            "SPI Mode 0",
        ):
            self.assertIn(phrase, rendered)
        self.assertNotIn("<image", rendered)
        self.assertNotIn("http://www.raspberrypi", rendered.lower())
        media_readme = (MEDIA_ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("original, repository-authored", media_readme)
        self.assertIn("MIT license", media_readme)
        self.assertIn("raspberry-pi-5-i2c-adxl355.svg", media_readme)
        self.assertIn("address `0x1D`", media_readme)

    def test_i2c_svg_is_accessible_local_and_matches_verified_fixture(self) -> None:
        tree = ET.parse(I2C_SVG)
        root = tree.getroot()
        namespace = {"svg": "http://www.w3.org/2000/svg"}
        title = root.find("svg:title", namespace)
        description = root.find("svg:desc", namespace)
        self.assertIsNotNone(title)
        self.assertIsNotNone(description)
        self.assertGreater(len((description.text or "").split()), 50)
        rendered = I2C_SVG.read_text(encoding="utf-8")
        for phrase in (
            "Pin 1 · 3V3",
            "Pin 6 · GND",
            "Pin 3 · GPIO2 / SDA1",
            "Pin 5 · GPIO3 / SCL1",
            "Pin 9 · GND (mode strap)",
            "Pin 14 · GND (address strap)",
            "Pin 11 · GPIO17 (optional)",
            "address 0x1D",
            "100 kHz",
        ):
            self.assertIn(phrase, rendered)
        self.assertNotIn("<image", rendered)
        self.assertNotIn("http://www.raspberrypi", rendered.lower())

    def test_hardware_guide_has_image_alt_text_and_text_equivalent(self) -> None:
        text = HARDWARE.read_text(encoding="utf-8")
        self.assertIn("media/raspberry-pi-5-spi-adxl355.svg", text)
        self.assertIn("media/raspberry-pi-5-i2c-adxl355.svg", text)
        self.assertRegex(text, r"!\[Verified Raspberry Pi 5 SPI wiring:")
        self.assertRegex(text, r"!\[Verified Raspberry Pi 5 I2C wiring:")
        self.assertIn("30734635341", text)
        self.assertIn("Only address `0x1D` is physically verified", text)
        for signal in ("`SCLK/VSSIO`", "`MOSI/SDA`", "`MISO/ASEL`", "`CS/SCL`"):
            self.assertIn(signal, text)
        self.assertIn("requirements/python/hil-spi.txt", text)
        self.assertIn("requirements/python/hil-i2c.txt", text)


if __name__ == "__main__":
    unittest.main()
