#!/usr/bin/env python3
"""Generate the C FIFO vector header from the authoritative JSON vectors."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "spec" / "test_vectors.json"
OUTPUT = ROOT / "c" / "tests" / "fifo_vectors.h"
ERRORS = {"length": 1, "empty": 2, "format": 3}


def render() -> str:
    fifo = json.loads(SOURCE.read_text(encoding="utf-8"))["fifo"]
    lines = [
        "/* Generated by spec/generate_fifo_vectors_header.py; do not edit. */",
        "#ifndef ADXL355_TEST_FIFO_VECTORS_H",
        "#define ADXL355_TEST_FIFO_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "enum { FIFO_VECTOR_ERROR_LENGTH = 1, FIFO_VECTOR_ERROR_EMPTY = 2, FIFO_VECTOR_ERROR_FORMAT = 3 };",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t bytes[9];",
        "    int32_t x;",
        "    int32_t y;",
        "    int32_t z;",
        "} fifo_valid_vector_t;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t bytes[10];",
        "    size_t length;",
        "    int expected_error;",
        "} fifo_invalid_vector_t;",
        "",
        "static const fifo_valid_vector_t FIFO_VALID_VECTORS[] = {",
    ]
    for vector in fifo["valid_samples"]:
        b = ", ".join(f"0x{x:02X}U" for x in vector["bytes"])
        raw = vector["raw"]
        lines.append(
            f'    {{"{vector["name"]}", {{{b}}}, INT32_C({raw["x"]}), '
            f"INT32_C({raw['y']}), INT32_C({raw['z']})}},"
        )
    lines.extend(
        ["};", "", "static const fifo_invalid_vector_t FIFO_INVALID_VECTORS[] = {"]
    )
    for vector in fifo["invalid_samples"]:
        padded = vector["bytes"] + [0] * (10 - len(vector["bytes"]))
        b = ", ".join(f"0x{x:02X}U" for x in padded)
        lines.append(
            f'    {{"{vector["name"]}", {{{b}}}, {len(vector["bytes"])}U, '
            f"{ERRORS[vector['error']]}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "#define FIFO_VALID_VECTOR_COUNT (sizeof(FIFO_VALID_VECTORS) / sizeof(FIFO_VALID_VECTORS[0]))",
            "#define FIFO_INVALID_VECTOR_COUNT (sizeof(FIFO_INVALID_VECTORS) / sizeof(FIFO_INVALID_VECTORS[0]))",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"{OUTPUT.relative_to(ROOT)} is stale")
        print(f"verified {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
