#!/usr/bin/env python3
"""Generate compact, source-derived API references for all maintained languages."""

from __future__ import annotations

import argparse
import difflib
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Final

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts.check_public_api import snapshot  # noqa: E402

OUTPUT_ROOT: Final = REPO_ROOT / "docs" / "api"
GENERATED_NOTICE: Final = (
    "<!-- Generated by scripts/generate_api_reference.py; edit public source "
    "declarations or the generator, not this file. -->"
)


class ReferenceError(RuntimeError):
    """Raised when generated API references are missing or stale."""


@dataclass(frozen=True)
class LanguageReference:
    key: str
    title: str
    package: str
    sources: tuple[str, ...]
    build_command: str
    capability: str
    limitations: str


LANGUAGES: Final = (
    LanguageReference(
        "c",
        "C API",
        "CMake target `adxl355::adxl355`",
        (
            "c/include/adxl355/adxl355.h",
            "c/include/adxl355/adxl355_registers.h",
            "c/include/adxl355/adxl355_version.h",
        ),
        "cmake -S c -B build/c && cmake --build build/c",
        "Core lifecycle, range, ODR, raw/converted reads, temperature, status, signed offsets, calibration helpers, and bounded self-test response.",
        "No public FIFO sample decoder, interrupt configuration API, or Linux bus adapter.",
    ),
    LanguageReference(
        "cpp",
        "C++ API",
        "CMake targets `adxl355::cpp` and `adxl355::cpp_noexcept`; root Arduino/PlatformIO package",
        (
            "cpp/include/adxl355/adxl355.hpp",
            "embedded/arduino/include/adxl355/arduino_spi.hpp",
            "embedded/README.md",
            "library.json",
        ),
        "cmake -S cpp -B build/cpp -DCMAKE_PREFIX_PATH=build/c-core && cmake --build build/cpp; pio run -d embedded/platformio/uno",
        "Owning exception and stack-owned no-exception wrappers over the C core for probe, reset, range, ODR, power mode, raw/converted reads, temperature, status, and stateless conversions; thin Arduino SPI compile integration.",
        "No public offset, calibration, self-test, FIFO, or interrupt wrapper. Arduino Uno support is compile-only and does not claim physical hardware validation or unbuilt boards/frameworks.",
    ),
    LanguageReference(
        "python",
        "Python API",
        "Distribution `adxl355`",
        (
            "python/src/adxl355/__init__.py",
            "python/src/adxl355/device.py",
            "python/src/adxl355/types.py",
            "python/src/adxl355/transport.py",
        ),
        "PYTHONPATH=python/src python -m pydoc adxl355",
        "Core lifecycle, range, ODR, FIFO entry count, raw/converted reads, temperature, status, signed offsets, calibration helpers, bounded self-test response, and Linux SPI/I2C adapters.",
        "No public FIFO sample decoder or interrupt/continuous-acquisition API.",
    ),
    LanguageReference(
        "rust",
        "Rust API",
        "Crate `adxl355-driver` / import `adxl355`",
        ("rust/src/lib.rs", "rust/src/device.rs", "rust/src/hal.rs"),
        "cargo doc --manifest-path rust/Cargo.toml --all-features --no-deps",
        "Core lifecycle, range, power mode, raw/converted reads, temperature, status, stateless conversions, and optional embedded-hal SPI/I2C adapters.",
        "No public ODR, offset, calibration, self-test, FIFO, or interrupt methods.",
    ),
    LanguageReference(
        "node",
        "Node.js / TypeScript API",
        "Package `@oaslananka/adxl355`",
        ("node/src/index.ts", "node/src/device.ts", "node/src/transport.ts"),
        "cd node && npm ci --ignore-scripts && npm run build",
        "Typed transport-agnostic core lifecycle, range, power mode, raw/converted reads, temperature, status, and stateless conversions.",
        "No maintained Linux SPI/I2C adapter and no public ODR, offset, calibration, self-test, FIFO, or interrupt methods.",
    ),
    LanguageReference(
        "go",
        "Go API",
        "Module `github.com/oaslananka/adxl355/go`",
        ("go/adxl355/device.go", "go/adxl355/transport.go", "go/adxl355/types.go"),
        "cd go && go doc ./adxl355",
        "Transport-agnostic core lifecycle, range, power mode, raw/converted reads, temperature, status, and stateless conversions.",
        "No maintained Linux SPI/I2C adapter and no public ODR, offset, calibration, self-test, FIFO, or interrupt methods.",
    ),
)


def source_link(path: str) -> str:
    return f"[`${path}`](../../{path})"


def split_entry(entry: str) -> tuple[str, str]:
    if ":" not in entry:
        return "declaration", entry
    category, declaration = entry.split(":", 1)
    return category.replace("_", " ").title(), declaration


def render_language(language: LanguageReference, entries: list[str]) -> str:
    groups: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        category, declaration = split_entry(entry)
        groups[category].append(declaration)

    lines = [
        GENERATED_NOTICE,
        "",
        f"# {language.title}",
        "",
        f"**Package:** {language.package}",
        "",
        "## Capability boundary",
        "",
        language.capability,
        "",
        f"**Not exposed:** {language.limitations}",
        "",
        "## Authoritative sources",
        "",
        *[f"- {source_link(path)}" for path in language.sources],
        "",
        "## Native documentation command",
        "",
        "```bash",
        language.build_command,
        "```",
        "",
        "## Public declarations",
        "",
        (
            "The declarations below are generated from the same normalized public API "
            "surface used by the compatibility gate. Source doc comments and language "
            "type systems remain authoritative for behavior and error details."
        ),
        "",
    ]
    for category in sorted(groups):
        lines.extend((f"### {category}", "", "```text"))
        lines.extend(sorted(groups[category]))
        lines.extend(("```", ""))
    return "\n".join(lines).rstrip() + "\n"


def render_index(surfaces: dict[str, list[str]]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        "# Public API references",
        "",
        (
            "These compact references are generated from repository public declarations. "
            "They make language-specific capability differences discoverable without "
            "committing full native documentation sites."
        ),
        "",
        "| Language | Reference | Public declarations | Capability summary |",
        "|---|---|---:|---|",
    ]
    for language in LANGUAGES:
        lines.append(
            f"| {language.title.removesuffix(' API')} | "
            f"[{language.key}.md]({language.key}.md) | "
            f"{len(surfaces[language.key])} | {language.capability} |"
        )
    lines.extend(
        (
            "",
            "## Regeneration and verification",
            "",
            "```bash",
            "python scripts/generate_api_reference.py",
            "python scripts/generate_api_reference.py --verify",
            "```",
            "",
            (
                "Native documentation output such as Rust HTML, Python `pydoc`, or build "
                "declaration files is transient and is not committed. The checked-in "
                "Markdown files stay small and are verified in required CI."
            ),
            "",
            "## Hardware setup media",
            "",
            (
                "The physically verified Raspberry Pi 5 SPI wiring diagram is available "
                "at [../media/raspberry-pi-5-spi-adxl355.svg]"
                "(../media/raspberry-pi-5-spi-adxl355.svg). I2C media remains pending "
                "physical I2C validation; see issue #41 and the hardware testing guide."
            ),
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def expected_outputs() -> dict[Path, str]:
    surfaces = snapshot(REPO_ROOT)["surfaces"]
    outputs = {OUTPUT_ROOT / "README.md": render_index(surfaces)}
    for language in LANGUAGES:
        outputs[OUTPUT_ROOT / f"{language.key}.md"] = render_language(
            language, surfaces[language.key]
        )
    return outputs


def generate() -> None:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in expected_outputs().items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def verify() -> None:
    stale: list[str] = []
    for path, expected in expected_outputs().items():
        if not path.is_file():
            stale.append(f"missing {path.relative_to(REPO_ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual == expected:
            continue
        diff = "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(path.relative_to(REPO_ROOT)),
                tofile="generated",
                n=2,
            )
        )
        stale.append(diff[:4000])
    expected_names = {path.name for path in expected_outputs()}
    unexpected = sorted(
        path.name
        for path in OUTPUT_ROOT.glob("*.md")
        if path.name not in expected_names
    )
    if unexpected:
        stale.append(f"unexpected generated API files: {unexpected}")
    if stale:
        raise ReferenceError("API references are stale:\n" + "\n".join(stale))
    print(f"verified {len(expected_outputs())} API reference files")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.verify:
            verify()
        else:
            generate()
            verify()
    except ReferenceError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
